### ISSUE TITLE
Site appears down often

### ISSUE THREAD

**Issue by tjsail33** [vkarpov15/mongooseplugins#8]
See Automattic/mongoose#3127. I frequently receive Application Errors when attempting to visit plugins.mongoosejs.com

**Comment by vkarpov15** [comment]
Fixed with #11. No more heroku.

**Comment by uptownhr** [comment]
FYI: the site currently appears down.

**Comment by vkarpov15** [comment]
Thanks, looks like I missed something: https://github.com/vkarpov15/mongooseplugins/commit/de5d4917607215a6bd114daf14ade97bdd706e58
